language: node_js

node_js:
- '8.15.0'

cache:
  directories:
  - node_modules

branches:
  only:
  - source

before_install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install

before_script:
- git config --global user.name 'Travis CI'
- git config --global user.email 'hexo@travis-ci.org'
- sed -i'' "s~git@github.com:sandersmee/sandersmee.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/sandersmee/sandersmee.github.io.git~" _config.yml

script:
- hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: source

env:
  global:
    secure: 0uXjiB6H2hjuf1oeDmZkbGikWXkVlG8zVz30EIWZ0FXOz9EAoKyvZWp72Cr6SONeE/AnEpWtwogka7hzcjTGNVc/lX3INxnx841k6w7Chw4B4R0twpso7kKGrCPp+dTBVi40lykAYC5oIMVOsYJ+vQCIPQxeX7PrIR6A9HAnR3cuWebKOCSyihuM8Kjvzk2K0S0LZBp+10mZ4q2ZfKtb3SsvuD7japTXhuT+pYb4Vs0MpE++dHjW8P5n59uR+XDTU98bwZWaPOdoBtNxjWSVQKNEYIlTewnr5hWKacRkTPrXE3vXPO4wZuYU0bJgSGVy4YbNNqQqcxCMMFMO8KraMv/To41a1I/NR69z+AI7odadsavRAyYl6acswvd5NQtp/ewuccUiqYmHFez8RC6a8G5oj/SPurli2E6Ih28cAPAoM4vO6tlWorgy8/DkW89urtMzJo07AcxwitMk/7OGX0kZ6yiZ29ihNr5u4RpYN+6Vyzr3BBjaob1xgQSnpEVfqUwLemOwvdDdEaCyhwc7kEQR2i99kBkzP/mSCvVlqJZTKaPuZj7JtvDhi96F1A/cIC8/123b2x+HCQA+vq3wZCPva0UpOQf4ZbaKZmrAj/wDPAtXdBZMO5UOQr/cdLLry6UKvjIATP4fIU2FtzlMWKOgPl8/oxCOWcx2oZvnShk=
