language: ruby
rvm:
- 2.5.1
cache: bundler
sudo: false
install:
- bundle install

script: bundle exec rake deploy

# safelist
branches:
  only:
  - source

env:
  global:
    secure: Hm3ceEnT8U7bY9kcFZW4rVL2LoYR+atOsmkhxZDTF+umQHlkVRJ/6crTgq11YxprEC/UQhODr5SHJh2/VJnz6Koscs9yPHD11v8HHNlHAinncAF39vfXcIWpEIh70ff9F3QQBOo10fbY4kzPyuCtrEw5zAwL6AhJkW8nAdG+mIpyuggVffuvZDG2a0KOhYMsIfE9iptKrqXYTKjgyvX0YVTOfn7y2CsXfN01NdBslJt0ABb8EoT7uCNWghbmsxeGGZQKGXLS16gKdjIFHkaK19+MkY8jNXS7Dh/7EO+Hgdx2EVv5u5tHDeWjVM8+htAjGFiCWJtL0N8x4nLZiX9E9ZxNgr21h2iEDobtOeUDM5zlqgVPIpuczyaTfFRTTgt1pUHzR5KidaS8CUKLAaNdFgG6KpndE1abcfiSJlMcJGHbZqidiw69OsC+ka2gwFl/nQeueyT+Uz1wgsCnkzfjs+aDdJUUMMH0Z7xfaoA105j5vgzVt3UbEt02nvglpIGOhgCNbKgsF+WxkOi1+wQvbrYFe8GsmsHf+blYN67xwNvOe5tltpxdb0nJg6SwJoGyiGJp9w7Cy9HbUAZTE147jQy7KkcE+7YSqE1A0s43xXFHNTsKk7iNjgDQJwtcJ1gPMVxEPElX6Pf1s2hIZKb9yYaREpW1Tamnd5KGNqD9c1w=
