language: node_js

node_js:
  - "16.13.2"

cache:
  directories:
    - node_modules

branches:
  only:
    - source

before_install:
  - npm install

before_script:
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'hexo@travis-ci.org'
  - sed -i'' "s~git@github.com:sandersmee/sandersmee.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/sandersmee/sandersmee.github.io.git~" _config.yml

script:
  - npx hexo generate

deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: source

env:
  global:
    secure: 0RH0wUOWOC16GQNfmiq7cejB3P52uLjdI+0b8IyuZS1Ewzp+04USH4AVFP6egSpHt/4urveXsoohyxY+P3wjKFS/Jwnp/dMmztQb2UmeEs9EMyxJoNX3q5ysGYavWLttlfDsmh/qappfzUaXG/0E37MGG8G45kSCUBAVC+c6BKvnDEMq6KpaejKEnhxZ/BicfF11uKMIaxnrroQxOsGTMMHDDQahOGerhuKUzaJBynChIBI8H/Uh6eJmE4L+rxvQrjdR+P2qNFDzpYW7ycpV+1lQukuwCAODViOsCa8O0j893sy1Q+j2GoFOpTuPw3qRO8DX8Z23fP9pRBpJmi1Elgiv2UGc6m3P6yj0ahFdz3XIL8RYtSGhAEnMp49zUBDy9kbgrOG57rAzwEOZbtmoX0+qOpw/53HlowobY1ME9sSf7g2TfKd/xiEoPr+c44RjcVl/M281lKsNkKOikGnlt2cMic8ERaWDDyLZSJ1eRUEscR8IUaOnUHh5DL3iGl0ZZWt6PEcLfvqsfMjPiTiKvgHECKD2wKhdUINrihi3X+hkiYVHk98dBvPNkC3hCDPb9bEsOwT0xaSRbAt9/qgMXEmBPoNESmo3ZBots1Nk5jPmhKtTa5vBZT2sTdy70E9cvTyIBbHkSmKOgxF2YTRUUPcc6HTKXTXbOPr1lG4kjOM=
