
# Site settings
title: Sander
email: sander.smeman@example.com
tagline: 'Java and Groovy Stuff'
description: 'What I learned about <a href="http://java.oracle.com" target="_blank">Java</a>, <a href="http://groovy.codehaus.org/" target="_blank">Groovy</a> and the world.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sandersmee.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: fongandrew/hydeout

asciidoctor:
  backend: html5s
  attributes:
    source-highlighter: rouge
    icons: font


google_analytics: UA-8287349-4
author:
  name: 'Sander'
  url: https://github.com/sandersmee

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-asciidoc
  - asciidoctor-rouge
  - asciidoctor-html5s

include: ['_pages']
permalink: /:year/:month/:title/

sidebar_home_link: true
