# Header
menu:
  About: /about
  Archive: /archives
  # Tags: /tags
  # Categories: /categories
  Github: https://github.com/SanderSmee/sandersmee.github.io

# Title on top left of menu. Leave empty to use main blog title
menu_title: thoughts.toString();

# URL of the Home page image
index_cover: //source.unsplash.com/dC6Pb2JdAqs

# Default post title
default_post_title: Untitled

# Google Analytics Tracking ID
google_analytics: UA-8287349-4

# set your own favicon
favicon:

# Social Accounts
footer:
  twitter_url: https://twitter.com/osusso
  twitter_handle: '@osusso'
  github_url: https://github.com/sandersmee/sandersmee.github.io
  linkedin_url: https://www.linkedin.com/in/sandersmeman/
  mailto: sander.smeman@gmail.com
